### ISSUE TITLE
Spirv-headers are not in correct locations with latest LunarG on linux

### ISSUE THREAD

**Issue by Steve132** [andy-thomason/Vookoo#17] opened 2019-10-26 20:57 UTC
Steps to reproduce:  install latest linux LunarG packages 

> wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.1.121-bionic.list http://packages.lunarg.com/vulkan/1.1.121/lunarg-vulkan-1.1.121-bionic.list
sudo apt update
sudo apt install vulkan-sdk

Then try to compile the examples:

> cmake ../examples/ && make

> /home/steven/Software/Vookoo/examples/../include/vku/vku.hpp:31:10: fatal error: vulkan/spirv.hpp11: No such file or directory
 #include <vulkan/spirv.hpp11>

This is because in the new lunarg SDK splits the spirv headers into a new project https://github.com/KhronosGroup/SPIRV-Headers

The new location for the headers in the lunarg sdk is `spirv/<version>`

> find /usr/include -name spirv.hpp11
/usr/include/spirv/unified1/spirv.hpp11
/usr/include/spirv/1.2/spirv.hpp11
/usr/include/spirv/1.0/spirv.hpp11
/usr/include/spirv/1.1/spirv.hpp11

**Comment by FunMiles** [comment] 2020-03-26 21:16
I have hit the same issue. I simply changed the include to:

`#include <spirv/unified1/spirv.hpp11>`

Is this project still alive? A pull request could be warranted if this work on every machine.
However there's also the issue that on Mac OS X, I am not finding this spirv.hpp11 file.
Can it be simply copied from Linux (I will have to try when I have a bit more time)

**Comment by lhog** [comment] 2020-03-27 09:07
Looks like vookoo is becoming a bit bitrotten, which is sad. I really liked the capabilities and code. @andy-thomason what's your plan for this repo?

**Comment by andy-thomason** [comment] 2020-03-27 09:25
If you want to make PRs, I'll be happy to accept them.

**Comment by andy-thomason** [comment] 2020-03-27 09:27
The motivation for Vookoo came from the need to make high framerate molecular simulators like https://github.com/andy-thomason/moovoo

**Comment by andy-thomason** [comment] 2020-03-27 09:29
I'm no longer working in the structural biology space but in statistical genetics and almost entirely in Rust, but I hope to return to Vulkan when the opportunity arises.

**Comment by lhog** [comment] 2020-03-28 10:05
@FunMiles @Steve132 cannot reproduce your issue.
I'm on Vulkan 1.2.131.2, which is latest at the time I write this. `spirv.hpp11` is still where it was before:
![image](https://user-images.githubusercontent.com/1476261/77820644-c8b72b80-70f4-11ea-9510-e6af20e37009.png)

**Comment by Steve132** [comment] 2020-03-28 19:11
https://github.com/KhronosGroup/SPIRV-Headers/tree/master/include/spirv

**Comment by lhog** [comment] 2020-03-29 08:56
For me `spirv.hpp11` in `include/vulkan` and `blabla/spirv/unified1` is exactly same.
![image](https://user-images.githubusercontent.com/1476261/77844851-aab00080-71b2-11ea-92d6-c546fbe53322.png)
I see it might be not the case for your OS/distribution.

I haven't been able to find any CMake file examples how to deal with finding relative path to `spir-v/unified1` in a cross-platform way. For you it's just `/usr/include`, but I'm not sure it's uniform for other Linux distributions.

**Comment by andy-thomason** [comment] 2020-03-31 13:26
I've made the spirv headers optional for now but did observe that the package glslang-dev on debian contains a SPIRV directory.

**Comment by andy-thomason** [comment] 2020-03-31 13:29
I would be remiss if I didn't mention the excellent Vulkano crate in the Rust ecosystem.
https://github.com/vulkano-rs/vulkano

**Comment by FunMiles** [comment] 2020-04-05 16:46
> For me `spirv.hpp11` in `include/vulkan` and `blabla/spirv/unified1` is exactly same.
> ![image](https://user-images.githubusercontent.com/1476261/77844851-aab00080-71b2-11ea-92d6-c546fbe53322.png)
> I see it might be not the case for your OS/distribution.
> 
> I haven't been able to find any CMake file examples how to deal with finding relative path to `spir-v/unified1` in a cross-platform way. For you it's just `/usr/include`, but I'm not sure it's uniform for other Linux distributions.

The MacOS X distribution of Vulkan/MoltenVK does not include the spirv includes. So Andy's work to make them optional have made it possible for me to easily port Vookoo to Mac OS. The README.md of Khronos SPIR-V headers says:

> Headers are provided in the include directory, with up-to-date headers in the unified1 subdirectory. Older headers are provided according to their version.

So it seems that the path `spirv/unified` path is the intended standard path.

**Comment by andy-thomason** [comment] 2020-04-06 10:15
While making the spirv headers optional has made this less of a problem, we should investigate restoring them once we have a definitive location and package list.

I'm going to close this for now.

**Closed as completed by andy-thomason** 2020-04-06 10:15 UTC

**Comment by FunMiles** [comment] 2020-04-06 13:44
I will look at this and try to address @lhog comment on how to find it. Perhaps trying to find the include from a series of possible paths and turning on/off a flag to indicate whether they were found would do the job. Then any example that require them should be removed from the build list.
